### PR TITLE
Feature/xxh plugin fish fisher initial work

### PR DESCRIPTION
**Pull request by frederickjh**
This plugin will install fisher and if a non-empty `fishfile` is found and it appears that no packages have yet been installed it will run `fisher` and install the packages in the `fishfile`. This allows for automatic installation of packages on xxh to a new host. The missing piece is a plugin to transfer user configuration like the `fishfile` to the remote host.

### CODE REVIEW

**Comment by anki-code** [comment]
Trying to test on [xxh-dev](https://github.com/xxh/xxh-dev):

1. First try (I've added github branch support in xxh 0.7.7):
```
ufish@start ~> xxh +RI xxh-plugin-fish-fisher+git+https://github.com/frederickjh/xxh-plugin-fish-fisher/tree/feature/xxh-plugin-fish-fisher_initial-work
cpio: command not found
```
Can you avoid using `cpio`?

2. After install cpio:
```
ufish@start ~> xxh +RI xxh-plugin-fish-fisher+git+https://github.com/frederickjh/xxh-plugin-fish-fisher/tree/feature/xxh-plugin-fish-fisher_initial-work
Remove xxh-plugin-fish-fisher
Removed /home/ufish/.xxh/.xxh/plugins/xxh-plugin-fish-fisher
Install xxh-plugin-fish-fisher+git+https://github.com/frederickjh/xxh-plugin-fish-fisher/tree/feature/xxh-plugin-fish-fisher_initial-work to local /home/ufish/.xxh/.xxh/plugins/xxh-plugin-fish-fisher
Git clone https://github.com/frederickjh/xxh-plugin-fish-fisher from branch 'feature/xxh-plugin-fish-fisher_initial-work'
Build xxh-plugin-fish-fisher
find: ‘pluginrc.fish’: No such file or directory
Installed /home/ufish/.xxh/.xxh/plugins/xxh-plugin-fish-fisher

ufish@start ~> ls /home/ufish/.xxh/.xxh/plugins/xxh-plugin-fish-fisher
build.sh*  config/  LICENSE  pluginrc.fish  README.md  requirements.txt
```
Here is `find: ‘pluginrc.fish’: No such file or directory`.

**Comment by frederickjh** [comment]
@anki-code Whoa! Sorry about that. It took me a bit to figure out what had happened. Looks like I was sitting in the folder where xxh builds the package before uploading them. Because of this relative paths to files to copy worked.  I have fixed this by now using absolute paths. I have tested this locally and then using the new github branch support.

As to not using `cpio` I hunted for solution for copying files that would also copy the directory structure they were in too, in other words something that would copy a directory tree and the files in it. `find` and `cpio` together work surprisingly well for this considering all the other pitiful sub-optimal solutions others offered to this task.

**Comment by anki-code** [comment]
I don't clearly understand why `cp -r dir1 dir2` is not working?

**Comment by anki-code** [comment]
1. Looks like `cpio` is a risk to get an error on remote host:
```
ufish@start ~> xxh -i id_rsa root@ubuntu_kf +s fish +if
...
Remove ubuntu_kf:/root/.xxh/.xxh
First time upload using rsync (this will be omitted on the next connections)
First run xxh-shell-fish on ubuntu_kf

~/.xxh/shells/xxh-shell-fish/build/../../../plugins/xxh-plugin-fish-fisher/build/pluginrc.fish (line 16): 
  find ".config/" -depth -print | cpio --quiet -pd  "$XXH_XDG_CONFIG_HOME" &>/dev/null
                                  ^
from sourcing file ~/.xxh/shells/xxh-shell-fish/build/../../../plugins/xxh-plugin-fish-fisher/build/pluginrc.fish
        called on line 14 of file ~/.xxh/shells/xxh-shell-fish/build/xxh-config.fish
from sourcing file ~/.xxh/shells/xxh-shell-fish/build/xxh-config.fish

Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
root@ubuntu_kf ~# 
```
I don't clearly understand why `cp -r dir1 dir2` is not working?

2. Could you add simple and useful example of using fisher to README? For example installing a new theme.

**Comment by frederickjh** [comment]
> I don't clearly understand why `cp -r dir1 dir2` is not working?

It is and for the fisher plugin it should work. 

The issue I was trying to solve with`cpio` is that `cp` does not create the needed directory tree to put the files in when it copies. However it should be possible with some `mkdir -p` commands to do this. I was trying to create code that could also be used for other plugins like the user config one I made that you do not know the files nor the directories that will need to be copied.

I still find it hard to believe that the functionality to create the need directory structure while copying files has never been added to `cp` or any other command line tool.

> 
>     1. Could you add simple and useful example of using fisher to README? For example installing a new theme.

Not sure it is needed as it is very simple and I also link to the Fisher page which has all that information on it. `fisher add acme/themname` is all it takes. If it is a repository on Github, but any git repository is supported by prefacing the domain name to the package.

**Comment by frederickjh** [comment]
I will see if I can replace the `find` and `cpio` with something like this:
```bash
mkdir -p /foo/bar && cp myfile "$_"
```

**Comment by anki-code** [comment]
Sorry but I still don't understand the problem case. Sometimes you should create the target directory before using `cp` but it is not the big cause to use non standard tool.

```
mkdir target_dir && cp source_dir target_dir     # copy source_dir to new target_dir
mkdir target_dir && cp source_dir/* target_dir   # copy all from source_dir to target_dir
```
Probably I don't understand what "create the need directory structure" means.

**Comment by frederickjh** [comment]
I am not sure I would call [`cpio`](https://www.gnu.org/software/cpio/manual/cpio.html) a non-standard tool. I found it all all the servers I checked. 

> cpio copies files into or out of a cpio or tar archive, The archive can be another file on the disk, a magnetic tape, or a pipe. 

> Probably I don't understand what "create the need directory structure" means.

Here is the directory structure for the plugin after building.

image

Note the directory structure in the build folder. If one tries to do ´cp fisher.fish config/fish/conf.d/` it will fail as none of those folder exists. One must first create them with `mkdir -p config/fish/conf.d/`.

I was not trying to be difficult, I was just trying to find code that could be used over again  in plugins without lots of lines. However I think that I can re-code this using the code I mention in my last post.

**Comment by anki-code** [comment]
I've added you as a maintainer of this repo. Feel free to merge.

**Comment by frederickjh** [comment]
:ok_hand: Thanks!  I want to see if I can replace `cpio` before merging this in, but I need to find time to work on this first.

**Comment by frederickjh** [comment]
I have decided to merge this and add an issue to replace `cpio`.

**Comment by anki-code** [comment]
Got it! I've added mention of fisher and userconfig to [the main xxh readme](https://github.com/xxh/xxh#shells).

**Pull request merged**
